//*********************************************************************\
// File name        : c4d_symbols.h
// Description      : symbol definition file for the plugin 
// Created at       : 
// Created by       : Resource editor
// Modified by      : 
//*********************************************************************/
// WARNING : Only edit this file, if you exactly know what you are doing.
// WARNING : The comments are important, too.

enum
{
  _FIRST_ELEMENT_      = 10000,
  // Dialog definitions of IDD_ROCK start here
  IDD_ROCK,
  IDC_RG_OPT,
  IDC_BANNER,
  IDC_LOD,
  IDC_CHK_SUBDIVS,
  IDC_CHK_ROUND,
  IDC_EDIT_SUBDIVS,
  IDC_CHK_STPRAND,
  IDC_EDIT_SEED,
  IDC_EDIT_DESTRUCT,
  IDC_EDIT_SHAPESMOOTH,
  IDC_EDIT_SCALE,
  IDC_MAT_OPT,
  IDC_REND_GROUP,
  IDC_REND_C4D,
  IDC_REND_VRAY,
  IDC_MAT_SELECT,
  IDC_MAT_GROUP,
  IDC_MAT_1,
  IDC_MAT_2,
  IDC_MAT_3,
  IDC_MAT_4,
  IDC_MAT_5,
  IDC_DISP_GROUP,
  IDC_ENABLE_DISP,
  IDC_DISP_AMT,
  IDC_DIST,
  GRP_SURFACE,
  IDC_OBJ_LINK,
  IDC_CHK_NORMALS,
  GRP_TRANS,
  IDC_OFF_X,
  IDC_OFF_Y,
  IDC_OFF_Z,
  IDC_SCALE_X,
  IDC_SCALE_Y,
  IDC_SCALE_Z,
  IDC_ROT_H,
  IDC_ROT_P,
  IDC_ROT_B,
  IDC_RAND_OFFSET,
  IDC_RAND_SCALE,
  IDC_RAND_ROT,
  GRP_MAT_DIST,
  IDC_RAND_MAT_DIST,
  IDC_BTN_APPLY,
  // Dialog definitions of IDD_ROCK end here

  // String table definition of IDD_ROCK starts here
  IDS_BUTTON,
  IDS_CHECK,
  IDS_CHECK12,
  IDS_CHECK15,
  IDS_CHECK18,
  IDS_CHECK2,
  IDS_CHECK22,
  IDS_CHECK3,
  IDS_CHECK4,
  IDS_CHECK8,
  IDS_DIALOG,
  IDS_RADIO13,
  IDS_RADIO14,
  IDS_RADIO4,
  IDS_RADIO5,
  IDS_RADIO6,
  IDS_RADIO7,
  IDS_RADIO8,
  IDS_STATIC,
  IDS_STATIC14,
  IDS_STATIC15,
  IDS_STATIC16,
  IDS_STATIC18,
  IDS_STATIC19,
  IDS_STATIC24,
  IDS_STATIC25,
  IDS_STATIC26,
  IDS_STATIC27,
  IDS_STATIC28,
  IDS_STATIC29,
  IDS_STATIC31,
  IDS_STATIC32,
  IDS_STATIC33,
  IDS_STATIC35,
  IDS_STATIC36,
  IDS_STATIC37,
  IDS_STATIC38,
  IDS_STATIC39,
  IDS_STATIC4,
  IDS_STATIC40,
  IDS_STATIC41,
  IDS_STATIC42,
  IDS_STATIC46,
  IDS_STATIC47,
  IDS_STATIC48,
  IDS_STATIC49,
  IDS_STATIC50,
  IDS_STATIC51,
  IDS_STATIC52,
  IDS_STATIC53,
  IDS_STATIC54,
  IDS_STATIC56,
  IDS_STATIC63,
  IDS_STATIC64,
  IDS_STATIC65,
  IDS_STATIC66,
  // String table definition of IDD_ROCK ends here


// End of symbol definition
  _DUMMY_ELEMENT_
};
