// C4D-DialogResource
DIALOG IDD_ROCK
{
  NAME IDS_DIALOG; SCALE_V; ALIGN_LEFT; 
  
  TAB IDC_STATIC
  {
    NAME IDS_STATIC28; ALIGN_TOP; FIT_H; 
    SELECTION_TABS; 
    
    GROUP IDC_RG_OPT
    {
      NAME IDS_STATIC4; FIT_V; FIT_H; SIZE 23, 256; 
      BORDERSIZE 4, 4, 4, 4; 
      COLUMNS 1;
      SPACE 4, 4;
      
      USERAREA IDC_BANNER { ALIGN_TOP; FIT_H; SIZE 100, 50; }
      GROUP IDC_LOD
      {
        NAME IDS_STATIC18; ALIGN_TOP; FIT_H; 
        BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 8; 
        ROWS 2;
        SPACE 4, 4;
        
        CHECKBOX IDC_CHK_SUBDIVS { NAME IDS_CHECK2; ALIGN_TOP; ALIGN_LEFT;  }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC16; ALIGN_TOP; ALIGN_LEFT; }
        CHECKBOX IDC_CHK_ROUND { NAME IDS_CHECK; ALIGN_TOP; ALIGN_LEFT;  }
        EDITSLIDER IDC_EDIT_SUBDIVS
        { CENTER_V; SCALE_H; SIZE 104, 0; }
      }
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC19; ALIGN_TOP; FIT_H; 
        BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 1;
        SPACE 4, 4;
        
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC27; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 0, 0, 0, 0; 
          COLUMNS 2;
          SPACE 4, 4;
          
          STATICTEXT IDC_STATIC { NAME IDS_STATIC26; CENTER_V; ALIGN_LEFT; }
          CHECKBOX IDC_CHK_STPRAND { NAME IDS_CHECK3; ALIGN_TOP; ALIGN_LEFT;  }
          EDITNUMBERARROWS IDC_EDIT_SEED
          { ALIGN_TOP; ALIGN_LEFT; SIZE 50, 0; }
        }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC; ALIGN_TOP; ALIGN_LEFT; SIZE 600, 0; }
        EDITSLIDER IDC_EDIT_DESTRUCT
        { ALIGN_TOP; SCALE_H; }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC15; ALIGN_BOTTOM; ALIGN_LEFT; SIZE 600, 10; }
        EDITSLIDER IDC_EDIT_SHAPESMOOTH
        { ALIGN_TOP; SCALE_H; }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC72; CENTER_V; ALIGN_LEFT; }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC67; ALIGN_TOP; FIT_H; 
          BORDERSTYLE BORDER_NONE; BORDERSIZE 4, 4, 4, 4; 
          COLUMNS 6;
          SPACE 4, 4;
          
          STATICTEXT IDC_STATIC { NAME IDS_STATIC68; CENTER_V; ALIGN_LEFT; }
          EDITNUMBERARROWS EDT_SCA_X
          { CENTER_V; CENTER_H; SIZE 70, 0; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC69; CENTER_V; ALIGN_LEFT; }
          EDITNUMBERARROWS EDT_SCA_Y
          { CENTER_V; CENTER_H; SIZE 70, 0; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC70; CENTER_V; ALIGN_LEFT; }
          EDITNUMBERARROWS EDT_SCA_Z
          { CENTER_V; CENTER_H; SIZE 70, 0; }
        }
      }
    }
    GROUP IDC_DIST
    {
      NAME IDS_STATIC36; ALIGN_TOP; FIT_H; 
      BORDERSIZE 4, 4, 4, 4; 
      COLUMNS 1;
      SPACE 4, 4;
      
      GROUP GRP_SURFACE
      {
        NAME IDS_STATIC37; ALIGN_TOP; SCALE_H; 
        BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 3;
        SPACE 4, 4;
        
        STATICTEXT IDC_STATIC { NAME IDS_STATIC38; CENTER_V; ALIGN_LEFT; }
        LINK IDC_OBJ_LINK
        {
          ALIGN_TOP; SCALE_H; 
        }
        CHECKBOX IDC_CHK_NORMALS { NAME IDS_CHECK18; ALIGN_TOP; ALIGN_LEFT;  }
      }
      GROUP GRP_TRANS
      {
        NAME IDS_STATIC39; ALIGN_TOP; SCALE_H; 
        BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 3;
        SPACE 4, 4;
        
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC46; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 4, 4, 4, 4; 
          COLUMNS 2;
          SPACE 4, 4;
          
          STATICTEXT IDC_STATIC { NAME IDS_STATIC40; CENTER_V; ALIGN_LEFT; }
          EDITNUMBERARROWS IDC_OFF_X
          { CENTER_V; CENTER_H; SIZE 70, 0; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC41; CENTER_V; ALIGN_LEFT; }
          EDITNUMBERARROWS IDC_OFF_Y
          { CENTER_V; CENTER_H; SIZE 70, 0; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC42; CENTER_V; ALIGN_LEFT; }
          EDITNUMBERARROWS IDC_OFF_Z
          { CENTER_V; CENTER_H; SIZE 70, 0; }
        }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC51; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 4, 4, 4, 4; 
          COLUMNS 2;
          SPACE 4, 4;
          
          STATICTEXT IDC_STATIC { NAME IDS_STATIC52; CENTER_V; ALIGN_LEFT; }
          EDITNUMBERARROWS IDC_SCALE_X
          { CENTER_V; CENTER_H; SIZE 70, 0; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC53; CENTER_V; ALIGN_LEFT; }
          EDITNUMBERARROWS IDC_SCALE_Y
          { CENTER_V; CENTER_H; SIZE 70, 0; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC54; CENTER_V; ALIGN_LEFT; }
          EDITNUMBERARROWS IDC_SCALE_Z
          { CENTER_V; CENTER_H; SIZE 70, 0; }
        }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC47; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 4, 4, 4, 4; 
          COLUMNS 2;
          SPACE 4, 4;
          
          STATICTEXT IDC_STATIC { NAME IDS_STATIC48; CENTER_V; ALIGN_LEFT; }
          EDITNUMBERARROWS IDC_ROT_H
          { CENTER_V; CENTER_H; SIZE 70, 0; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC49; CENTER_V; ALIGN_LEFT; }
          EDITNUMBERARROWS IDC_ROT_P
          { CENTER_V; CENTER_H; SIZE 70, 0; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC50; CENTER_V; ALIGN_LEFT; }
          EDITNUMBERARROWS IDC_ROT_B
          { CENTER_V; CENTER_H; SIZE 70, 0; }
        }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC56; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 4, 4, 4, 4; 
          COLUMNS 1;
          SPACE 4, 4;
          
          CHECKBOX IDC_RAND_OFFSET { NAME IDS_CHECK8; ALIGN_TOP; ALIGN_LEFT;  }
        }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC63; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 4, 4, 4, 4; 
          COLUMNS 1;
          SPACE 4, 4;
          
          CHECKBOX IDC_RAND_SCALE { NAME IDS_CHECK12; ALIGN_TOP; ALIGN_LEFT;  }
        }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC64; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 4, 4, 4, 4; 
          COLUMNS 1;
          SPACE 4, 4;
          
          CHECKBOX IDC_RAND_ROT { NAME IDS_CHECK15; ALIGN_TOP; ALIGN_LEFT;  }
        }
      }
      GROUP GRP_MAT_DIST
      {
        NAME IDS_STATIC65; ALIGN_TOP; SCALE_H; 
        BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 1;
        SPACE 4, 4;
        
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC66; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 4, 4, 4, 4; 
          COLUMNS 1;
          SPACE 4, 4;
          
          CHECKBOX IDC_RAND_MAT_DIST { NAME IDS_CHECK22; ALIGN_TOP; ALIGN_LEFT;  }
        }
      }
    }
  }
  BUTTON IDC_BTN_APPLY { NAME IDS_BUTTON; CENTER_V; CENTER_H; SIZE 200, 16; }
}